my portfolio
bertinkambale/My-professional-portfolio pull request #1
Opened 2022-05-26 20:18 UTC by bertinkambale

this project will display my portfolio

2022-05-26 22:26 UTC, phelian23 requested changes
Hi @bertinkambale, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 22:26 UTC, phelian23 commented on index.html
> +            <h4>My logo</h4>
- [ ]  Kindly wrap the logo in an `<a>`, it is a good practice to wrap the logo in an `<a>` as this will serve as a link to the home from anywhere on the page.

2022-05-26 22:26 UTC, phelian23 commented on index.html
> +            </div>
- [ ] Kindly make use of the `<ul>` and `<li>` tags to wrap the list of icons. e.g.
``` javascript
  <ul>
     <li><a.....>.....</a></li>
  <ul>
```

2022-05-26 22:26 UTC, phelian23 commented on index.html
> +            <h2>I’m Bertin <br>Glad to see<br> you!</h2>
- [ ] Kindly change the `<h2>` tag here to `<h1>` as this is the main title of the mage

2022-05-27 11:02 UTC, m05e5 approved these changes
# Hi @bertinkambale , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


- _(optional)_ Great job. i only recommend fixing this image too
![image](https://user-images.githubusercontent.com/37901469/170683281-adc1c634-b8d1-4db8-8e0f-2cf0aabc8afe.png)

- _(optional)_ Please kindly remove the node modules from the git repo. you can follow this [guide](https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-a-git-repository)

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 12:09 UTC, merged