i want to add a contact form and finish the mobile version
bertinkambale/My-professional-portfolio pull request #4
Opened 2022-05-31 17:45 UTC by bertinkambale

For this third milestone of my portfolio website, I will:

- I will add a contact form for my portfolio and the portfolio.
-I make sure that I  guide users' experience in a way that helps them fill in the form without frustration.

2022-06-02 11:02 UTC, elhamatokhi reviewed
Great job so far!

- Try to remove extra spaces in both HTML and CSS files, it will help you fix linter errors.

2022-06-03 10:47 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @bertinkambale 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Rewquired changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 10:47 UTC, tresorsawasawa commented on index.html
> +      <section class="my-second-section container">
[ **OPTIONAL** ] I think it would be better to add a `spacing(margin-top)` at the top of your sections. I noticed that your cards overlap content in the `heading section`. I suggest you check from Figma the right spacing between the two sections. Please, don't care about the border on the Figma image, but the **spacing between sections**
| Figma design | Your design |
| ------------------------ | ----------------- |
| ![fc](https://user-images.githubusercontent.com/83042742/171833217-cf8bd471-4810-4a09-bd71-e325b5597042.png) | ![c](https://user-images.githubusercontent.com/83042742/171832921-c0ddfefd-ad39-4cef-8f9b-9fa4a3792201.png) |

2022-06-03 10:47 UTC, tresorsawasawa commented on style.css
>  }
- [ ] Good job with your design, it looks smart. I just noticed that there is still a small thing to fix in the `textarea field`. I suggest you use the appropriate `font-family` as from the Figma design.
- [ ] Once you fixed the issue above, kindly make sure you added everything in the `contact form`. I noticed that it misses the `horizontal line` at the **bottom**. You can take a look at the below images. Complete those issues will make your project stick to the Figma template as much as possible.
### Figma Design
![bottom](https://user-images.githubusercontent.com/83042742/171835807-6a2943ba-bbf7-4e20-a2b2-555941924918.png)
### You design 
![sb](https://user-images.githubusercontent.com/83042742/171835728-bfa8a68e-7ad2-4280-b76d-dfd9474ce346.png)

2022-06-03 10:47 UTC, tresorsawasawa commented on index.html
> +            </button>
- [ ] Good job by adding the hover mode interaction on your `Get in Touch` button. So, I noticed that the used color is not the expected one like from Figma. I suggest all your `button(Get in Touch)` and `See Project` buttons have interactions such as **hover**, **active** (when it's pressed),... styled as shown in the Figma template, and also check the used `font-size`.
To make it simple you can create a class like `interactive-button` then style it according to the behavior, then add it to each button. e.g. :
````bash
.interactions-button:hover {
    put your code here
}

.interactive-button:active {
  put your code here
}
```

2022-06-03 10:47 UTC, tresorsawasawa commented on index.html
> +    </div>
- [ **OPTIONAL** ] For good semantics of HTML, I suggest you use the `<footer>` tag as the container instead of the **div** to make your code more organized. i.e change `<div>` to `<footer>` to make it looks better.

2022-06-03 23:32 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @bertinkambale  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 00:22 UTC, merged