Desktop Version
bertinkambale/My-professional-portfolio pull request #5
Opened 2022-06-02 06:25 UTC by bertinkambale

For the fourth project on my portfolio website, I will:

- Use media queries to make sure that your website displays correctly on desktop screens.

2022-06-03 23:30 UTC, Kandy-Peter requested changes
Hi @ManarOmari 

Good job so far! I know you have worked hard on making this milestone. There is an issue that you still need to work on to go to the next project but you are almost there!

![almost-there-almost](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 23:30 UTC, Kandy-Peter commented on index.html
> +     </div>
- [ ] Kindly, ensure that you align your card's child element to match the Figma design

- Hint: You can use the CSS property `object_fit: contain` to fit your image and ensure that they don't exceed their containers.

**1. Your cards**
![image](https://user-images.githubusercontent.com/80612925/171965150-b93cdaa5-4215-4c90-9877-be1f7accf32a.png)
**2.Figma design**
![image](https://user-images.githubusercontent.com/80612925/171965224-ee6f38a9-aa7d-49a8-aa30-48893b0a8cd7.png)

2022-06-03 23:30 UTC, Kandy-Peter commented on index.html
> +            </section>
- [ ] As required, your template should stick as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). In your case you missed some points. 

1. Please, use the same `font` and `color` for your text.
2. It would be nice if you align your languages and add their respective `background` to stick to the Figma design.
3. Ensure that you aling your social icons to the left of your page.
4. For this section, you will also need to add a `border-radius` to the top-right corner to stick the design as well

![image](https://user-images.githubusercontent.com/80612925/171965884-7066e72b-dcd3-4d60-b858-de1631dab200.png)

**2.The Figma design**
![image](https://user-images.githubusercontent.com/80612925/171966032-0790cfb3-efe4-4c24-9cf7-c6cc8c1c9fea.png)

2022-06-03 23:30 UTC, Kandy-Peter commented on index.html
> +
- [ ] For a better look and to make your design too beautiful 😊, I would suggest you enlarge your form and use the same `font` provided in the Figma design for your subtitle `Contact me`.
![image](https://user-images.githubusercontent.com/80612925/171966415-1229e770-4500-4770-ba7b-39a4df96ff49.png)

**Figma design**
![image](https://user-images.githubusercontent.com/80612925/171966472-70b927e4-999c-4cfd-810e-dd8b5fbf2f9b.png)

2022-06-04 10:39 UTC, aimemalaika approved these changes
Hi @bertinkambale , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 11:27 UTC, merged